name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.1.0
  image_picker: ^1.1.0
  image_cropper_plus:
    path: ../../image_cropper_plus

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
