name: image_cropper_plus_for_web
description: A Flutter plugin for Web supports cropping images
repository: https://github.com/ahyangnb/flutter_image_cropper_plus
version: 4.0.1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  image_cropper_plus_platform_interface: ^5.0.1

  js: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperPlugin
        fileName: image_cropper_plus_for_web.dart
